# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server2game.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11server2game.proto\x12\x07traffic\x1a\x0c\x63ommon.proto\"\xe5\x01\n\rFightStartReq\x12\x12\n\nlevel_name\x18\x01 \x02(\t\x12$\n\tjunctions\x18\x02 \x03(\x0b\x32\x11.traffic.Junction\x12 \n\x07signals\x18\x03 \x03(\x0b\x32\x0f.traffic.Signal\x12\x1c\n\x05\x65\x64ges\x18\x04 \x03(\x0b\x32\r.traffic.Edge\x12)\n\x0clane_configs\x18\x05 \x03(\x0b\x32\x13.traffic.LaneConfig\x12/\n\x0fvehicle_configs\x18\x06 \x03(\x0b\x32\x16.traffic.VehicleConfig\"\x0f\n\rFightStartRsp\"R\n\x0cStepFrameReq\x12.\n\x0b\x66rame_state\x18\x01 \x02(\x0b\x32\x19.traffic.FrameStateNature\x12\x12\n\nterminated\x18\x02 \x02(\x05\"K\n\x0cStepFrameRsp\x12(\n\x08\x63md_list\x18\x01 \x03(\x0b\x32\x16.traffic.AICommandInfo\x12\x11\n\tgame_over\x18\x02 \x01(\x05\"\x0b\n\tFinishReq\"\x0b\n\tFinishRsp\"\\\n\x10\x46rameStateNature\x12\x10\n\x08\x66rame_no\x18\x01 \x02(\r\x12\x12\n\nframe_time\x18\x02 \x02(\r\x12\"\n\x08vehicles\x18\x03 \x03(\x0b\x32\x10.traffic.Vehicle\"\xab\x01\n\tGameFrame\x12\x0f\n\x07game_id\x18\x01 \x02(\t\x12\x10\n\x08\x66rame_no\x18\x02 \x02(\r\x12.\n\x0b\x66rame_state\x18\x03 \x02(\x0b\x32\x19.traffic.FrameStateNature\x12\x12\n\nterminated\x18\x04 \x02(\x08\x12\x11\n\ttruncated\x18\x05 \x02(\x08\x12$\n\tgame_info\x18\x06 \x02(\x0b\x32\x11.traffic.GameInfo\"\xcc\x01\n\x08GameInfo\x12$\n\tjunctions\x18\x01 \x03(\x0b\x32\x11.traffic.Junction\x12 \n\x07signals\x18\x02 \x03(\x0b\x32\x0f.traffic.Signal\x12\x1c\n\x05\x65\x64ges\x18\x03 \x03(\x0b\x32\r.traffic.Edge\x12)\n\x0clane_configs\x18\x04 \x03(\x0b\x32\x13.traffic.LaneConfig\x12/\n\x0fvehicle_configs\x18\x05 \x03(\x0b\x32\x16.traffic.VehicleConfig')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server2game_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FIGHTSTARTREQ']._serialized_start=45
  _globals['_FIGHTSTARTREQ']._serialized_end=274
  _globals['_FIGHTSTARTRSP']._serialized_start=276
  _globals['_FIGHTSTARTRSP']._serialized_end=291
  _globals['_STEPFRAMEREQ']._serialized_start=293
  _globals['_STEPFRAMEREQ']._serialized_end=375
  _globals['_STEPFRAMERSP']._serialized_start=377
  _globals['_STEPFRAMERSP']._serialized_end=452
  _globals['_FINISHREQ']._serialized_start=454
  _globals['_FINISHREQ']._serialized_end=465
  _globals['_FINISHRSP']._serialized_start=467
  _globals['_FINISHRSP']._serialized_end=478
  _globals['_FRAMESTATENATURE']._serialized_start=480
  _globals['_FRAMESTATENATURE']._serialized_end=572
  _globals['_GAMEFRAME']._serialized_start=575
  _globals['_GAMEFRAME']._serialized_end=746
  _globals['_GAMEINFO']._serialized_start=749
  _globals['_GAMEINFO']._serialized_end=953
# @@protoc_insertion_point(module_scope)
